"""Shared private helpers used by multiple ``check_*`` modules.

Single-use helpers stay in the per-check module that needs them. Helpers
imported by two or more check modules — or by callers outside
``validator/checks/`` — land here so each check file stays tight.
"""

from __future__ import annotations

import re
import uuid as _uuid
from pathlib import Path
from typing import Any

import yaml

from tripwire.core import paths
from tripwire.core.validator._types import CheckResult, ValidationContext
from tripwire.models.manifest import ArtifactManifest

# ---------------------------------------------------------------------------
# Identity: pre-load UUID v4 check (used by every entity loader in
# ``validator/__init__.py``; not by any post-load ``check_*`` function).
# ---------------------------------------------------------------------------


def uuid_v4_load_error(
    *, kind: str, rel_path: str, raw_frontmatter: dict[str, Any]
) -> CheckResult | None:
    """Return ``uuid/not_v4`` if raw uuid isn't RFC 4122 v4, else ``None``.

    Loaders call this BEFORE handing the frontmatter to Pydantic. Entity
    models are typed ``UUID4``, so a non-v4 value would otherwise surface
    as the generic ``<kind>/schema_invalid`` and the catalogue would lose
    specificity (KUI-143).

    A missing uuid is NOT this check's concern — the loader still hands
    the entity to Pydantic (which fills the default), and the post-load
    ``check_uuid_present`` reports ``uuid/missing`` from raw frontmatter.
    """
    raw = raw_frontmatter.get("uuid")
    if raw is None:
        return None
    try:
        parsed = _uuid.UUID(str(raw))
    except (ValueError, AttributeError, TypeError):
        return CheckResult(
            code="uuid/not_v4",
            severity="error",
            file=rel_path,
            field="uuid",
            message=f"{kind} uuid {raw!r} is not a valid UUID.",
            fix_hint="Replace with a UUID generated by `tripwire uuid`.",
        )
    if parsed.version != 4 or parsed.variant != _uuid.RFC_4122:
        return CheckResult(
            code="uuid/not_v4",
            severity="error",
            file=rel_path,
            field="uuid",
            message=(
                f"{kind} uuid {raw!r} is not RFC 4122 v4 "
                f"(version={parsed.version}, variant={parsed.variant!r})."
            ),
            fix_hint="Replace with a UUID generated by `tripwire uuid`.",
        )
    return None


# ---------------------------------------------------------------------------
# Artifacts: manifest loader shared by manifest_schema /
# manifest_phase_ownership_consistent / artifact_presence (and by
# ``validator/_manifest_lookup.py``).
# ---------------------------------------------------------------------------


def _load_manifest(
    ctx: ValidationContext,
) -> tuple[ArtifactManifest | None, list[CheckResult]]:
    """Parse `templates/artifacts/manifest.yaml` via the shared loader.

    Returns (manifest, findings). A missing manifest file is not an error
    (returns `(None, [])`). YAML parse errors, schema violations, and enum
    violations (unknown `produced_at` / `produced_by` / `owned_by`) surface
    as `manifest_schema/*` findings so `check_manifest_schema` can emit them.
    """
    from tripwire.core.manifest_loader import load_artifact_manifest

    manifest_path = paths.templates_artifacts_manifest_path(ctx.project_dir)
    rel = paths.TEMPLATES_ARTIFACTS_MANIFEST
    manifest, load_findings = load_artifact_manifest(ctx.project_dir, manifest_path)
    findings = [
        CheckResult(
            code=f.code,
            severity="error",
            file=rel,
            field=f.field,
            message=f.message,
        )
        for f in load_findings
    ]
    return manifest, findings


# ---------------------------------------------------------------------------
# Coherence: pm-response manifest gate shared by the two pm_response checks.
# ---------------------------------------------------------------------------


def _pm_response_produced_at(ctx: ValidationContext) -> str | None:
    """Thin wrapper over the shared `artifact_entry` helper for the
    `pm-response` manifest entry's `produced_at`.

    Kept as a named helper for readability at call sites; new artifact-
    shaped rules should use `artifact_entry(ctx, name)` directly.
    """
    from tripwire.core.validator._manifest_lookup import artifact_entry

    entry = artifact_entry(ctx, "pm-response")
    return entry.produced_at if entry is not None else None


# ---------------------------------------------------------------------------
# PR-review (v0.12): placeholder detection + manifest gate + config reader.
# All four pr_review checks consume these.
# ---------------------------------------------------------------------------

_PLACEHOLDER_PATTERNS = [
    re.compile(r"^manual verification needed$", re.IGNORECASE),
    re.compile(r"^<.*>$"),  # < anything > placeholder
    re.compile(r"^tbd$", re.IGNORECASE),
    re.compile(r"^todo$", re.IGNORECASE),
    re.compile(r"^—$"),  # em-dash
    re.compile(r"^-$"),
]
"""Regex patterns recognised as placeholder text in `verified_by`.

Any AC whose `verified_by` array is empty, OR contains an entry
matching any of these patterns, OR contains an entry shorter than 8
characters, fails the missing_evidence check.
"""


def _is_placeholder(evidence: str) -> bool:
    """Is this `verified_by` string a placeholder?"""
    s = (evidence or "").strip()
    if len(s) < 8:
        return True
    return any(p.match(s) for p in _PLACEHOLDER_PATTERNS)


def _load_pr_review(session_dir: Path, file: str) -> dict[str, Any] | None:
    """Read pr-review.yaml from either layout. Returns parsed dict or None."""
    from tripwire.core.validator._manifest_lookup import find_artifact_on_disk

    path = find_artifact_on_disk(session_dir, file)
    if path is None:
        return None
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (yaml.YAMLError, OSError):
        return None
    return data if isinstance(data, dict) else None


def _gate(ctx: ValidationContext) -> tuple[str, str] | None:
    """Look up the pr-review manifest entry and return
    `(threshold, file)` for callers to gate on. Returns None if the
    entry isn't manifested (skip check)."""
    from tripwire.core.validator._manifest_lookup import artifact_entry

    entry = artifact_entry(ctx, "pr-review")
    if entry is None:
        return None
    return entry.produced_at, entry.file


def _at_or_past(ctx: ValidationContext, status: str, threshold: str) -> bool:
    """Wraps `status_at_or_past` with the artifact_phase → session_status
    mapping and the session_status enum."""
    from tripwire.core.issue_artifact_store import status_at_or_past
    from tripwire.core.validator._manifest_lookup import phase_to_session_status

    return status_at_or_past(
        status,
        phase_to_session_status(threshold),
        ctx.project_dir,
        enum_name="session_status",
    )


def _get_review_config(ctx: ValidationContext) -> dict[str, Any]:
    """Read `project.yaml.review` as a plain dict for graceful fallback
    (older projects without the v0.12 field still validate)."""
    if ctx.project_config is None:
        return {}
    review = getattr(ctx.project_config, "review", None)
    if review is None:
        return {}
    if hasattr(review, "model_dump"):
        return review.model_dump()
    return dict(review) if isinstance(review, dict) else {}


# ---------------------------------------------------------------------------
# Session-lifecycle: enum-aware at-or-past helpers + shared per-issue
# artifact scan used by check_session_has_developer_md /
# check_session_has_verified_md.
# ---------------------------------------------------------------------------


def _session_at_or_past(ctx: ValidationContext, current: str, threshold: str) -> bool:
    """Return True when ``current`` ≥ ``threshold`` in the project's
    ``session_status`` enum order. Side states (paused/abandoned/...)
    are off-lifecycle and never count as "reached".
    """
    from tripwire.core.issue_artifact_store import status_at_or_past

    return status_at_or_past(
        current, threshold, ctx.project_dir, enum_name="session_status"
    )


def _issue_at_or_past(ctx: ValidationContext, current: str, threshold: str) -> bool:
    """Same as ``_session_at_or_past`` but reads the ``issue_status`` enum."""
    from tripwire.core.issue_artifact_store import status_at_or_past

    return status_at_or_past(
        current, threshold, ctx.project_dir, enum_name="issue_status"
    )


def _issue_artifacts_for_session(
    ctx: ValidationContext, artifact_name: str
) -> list[CheckResult]:
    """Shared body: every member issue of a session must ship the named
    issue-artifact once the issue has reached the manifest's gate status.

    ``artifact_name`` selects which manifest entry — ``"developer"`` or
    ``"verified"`` — drives the check. The validator id and finding code
    are derived from the caller's choice in the public ``check_*``
    wrappers.
    """
    from tripwire.core.issue_artifact_store import load_issue_artifact_manifest
    from tripwire.core.store import load_issue

    results: list[CheckResult] = []
    try:
        manifest = load_issue_artifact_manifest(ctx.project_dir)
    except FileNotFoundError:
        return results
    except Exception:
        # Schema problems surface from check_issue_artifact_presence /
        # check_manifest_schema — don't double-fire here.
        return results

    entry = next((e for e in manifest.artifacts if e.name == artifact_name), None)
    if entry is None or not entry.required:
        return results

    code = f"session/{artifact_name}_md_missing"
    for s_entity in ctx.sessions:
        session = s_entity.model
        sid = session.id
        for issue_key in session.issues:
            try:
                issue = load_issue(ctx.project_dir, issue_key)
            except FileNotFoundError:
                continue
            if not _issue_at_or_past(ctx, issue.status, entry.required_at_status):
                continue
            artifact_path = (
                paths.issue_docs_dir(ctx.project_dir, issue_key) / entry.file
            )
            rel_path = (
                f"{paths.ISSUES_DIR}/{issue_key}/{paths.ISSUE_DOCS_SUBDIR}/{entry.file}"
            )
            if artifact_path.is_file():
                continue
            results.append(
                CheckResult(
                    code=code,
                    severity="error",
                    file=rel_path,
                    message=(
                        f"Session {sid!r} member issue {issue_key!r} ({issue.status}) "
                        f"is at-or-past {entry.required_at_status!r} but is missing "
                        f"required artifact {entry.file!r}."
                    ),
                    fix_hint=(f"Write {rel_path} from {entry.template}."),
                )
            )
    return results
